# Generated by Django 4.2.7 on 2024-01-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiphopapi', '0005_remove_user_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_closed',
            new_name='closed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cashier',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
