# Generated by Django 4.2.7 on 2024-01-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiphopapi', '0008_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
